language: rust
cache: cargo
jobs:
  include:
    - name: "Unit tests & sdist"
      dist: bionic
      before_install:
        - sudo apt-get -y install python3-pip
      script: |
              python3 setup.py bdist_wheel
              python3 setup.py sdist
              pip install dist/*.whl
              # FIXME: also run unit tests once they are not network based
    - name: "Linux"
      if: tag IS present
      services: docker
      dist: bionic
      before_install:
        - sudo apt-get -y install python3-pip
    - name: "macOS"
      if: tag IS present
      os: osx
      osx_image: xcode11
    - name: "Windows"
      if: tag IS present
      os: windows           # Windows 10.0.17134 N/A Build 17134
      before_install:
        - choco install python --version 3.8.0
        - choco install strawberryperl
        - python -m pip install --upgrade pip
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH
env:
  global:
    - CIBW_BEFORE_ALL_LINUX="curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y"
    - CIBW_BEFORE_BUILD="pip install -U setuptools-rust"
    - CIBW_BUILD_VERBOSITY="1"   # Make some more noise so that travis doesn't stall
    - CIBW_ENVIRONMENT='PATH="$PATH:$HOME/.cargo/bin"'
    - CIBW_SKIP="cp27-* cp34-* cp35-* pp* *-win32"
install:
    - |
      pip3 install --upgrade pip wheel setuptools setuptools-rust
      pip3 install --upgrade pip cibuildwheel
script:
    - |
      if [ "$TRAVIS_OS_NAME" = "windows" ]; then
          # XXX Disabled for now rustup target add i686-pc-windows-msvc
          python -m cibuildwheel --output-dir wheelhouse
      else
          python3 -m cibuildwheel --output-dir wheelhouse
      fi
deploy:
  provider: releases
  api_key: $RELEASE_TOKEN
  file_glob: true
  skip_cleanup: true
  file:
    - wheelhouse/*  # wheels
    - dist/*.tar.gz  # sdist
  draft: true
  on:
      tag: true
  name: $TRAVIS_TAG (DRAFT)
